# Generated by Django 5.2.6 on 2025-10-03 05:11

import uuid
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.indexes import GistIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Ensure pg_trgm extension is available
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, verbose_name='分类名称')),
                ('language', models.CharField(choices=[('zh-CN', '简体中文'), ('zh-HK', '繁體中文（香港）'), ('en', 'English')], default='zh-CN', help_text='Content language', max_length=35, verbose_name='语言')),
                ('translation_group', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID linking translations of the same category', verbose_name='翻译组')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from name if empty)', max_length=100, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='描述')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Wiki Category',
                'verbose_name_plural': 'Wiki Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('slug', 'language')},
                'indexes': [
                    models.Index(fields=['language', 'order'], name='wiki_cat_lang_order_idx'),
                    models.Index(fields=['translation_group'], name='wiki_cat_trans_grp_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from title if empty)', max_length=200, verbose_name='URL Slug')),
                ('language', models.CharField(choices=[('zh-CN', '简体中文'), ('zh-HK', '繁體中文（香港）'), ('en', 'English')], default='zh-CN', help_text='Content language', max_length=35, verbose_name='语言')),
                ('translation_group', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID linking translations of the same page', verbose_name='翻译组')),
                ('content', models.TextField(help_text='Page content in Markdown format', verbose_name='内容')),
                ('summary', models.TextField(blank=True, help_text='Brief summary for listings (max 500 characters)', max_length=500, verbose_name='摘要')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'tutorial, beginner, setup')", max_length=200, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿 / Draft'), ('published', '已发布 / Published')], default='draft', help_text='Page status (draft or published)', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this page has been viewed', verbose_name='浏览次数')),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)', verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='Page author', on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, help_text='Page category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='wiki.wikicategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'verbose_name_plural': 'Wiki Pages',
                'ordering': ['-updated_at'],
                'unique_together': {('slug', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['slug', 'language'], name='wiki_page_slug_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['status', '-updated_at'], name='wiki_page_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['category', 'order'], name='wiki_page_cat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['language', '-updated_at'], name='wiki_page_lang_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['translation_group'], name='wiki_page_trans_grp_idx'),
        ),
        migrations.AddConstraint(
            model_name='wikicategory',
            constraint=models.UniqueConstraint(
                fields=['translation_group', 'language'], name='wiki_cat_trans_lang_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(
                fields=['translation_group', 'language'], name='wiki_page_trans_lang_unique'
            ),
        ),
        # Add trigram indexes for better search performance
        migrations.AddIndex(
            model_name='wikipage',
            index=GistIndex(fields=['title'], name='wikipage_title_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=GistIndex(fields=['content'], name='wikipage_content_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=GistIndex(fields=['summary'], name='wikipage_summary_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=GistIndex(fields=['tags'], name='wikipage_tags_trgm_idx', opclasses=['gist_trgm_ops']),
        ),
    ]
