# Generated by Django 5.2.6 on 2025-10-03 05:11

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Enable pg_trgm extension for trigram similarity search
        TrigramExtension(),
    ]

