# Generated by Django 5.2.6 on 2025-10-03 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Ensure pg_trgm extension is available
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="展示昵称（唯一）", max_length=15, unique=True
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, help_text="头像 URL，可为空"),
                ),
                (
                    "pronouns",
                    models.CharField(blank=True, help_text="用户代词，可为空", max_length=100),
                ),
                (
                    "show_forum_posts_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum posts"),
                ),
                (
                    "show_forum_post_comments_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum post comments"),
                ),
                (
                    "show_course_reviews_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的course reviews"),
                ),
                (
                    "last_nickname_updated_at",
                    models.DateTimeField(blank=True, help_text="最后一次修改昵称的时间", null=True),
                ),
                (
                    "is_account_active",
                    models.BooleanField(default=True, help_text="账户是否激活（允许登录）"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        # Add trigram index for better search performance on nickname
        migrations.AddIndex(
            model_name='profile',
            index=GinIndex(fields=['nickname'], name='profile_nickname_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
