# Generated by Django 5.2.6 on 2025-09-22 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="展示昵称（不唯一）", max_length=100
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, help_text="头像 URL，可为空"),
                ),
                (
                    "pronouns",
                    models.CharField(blank=True, help_text="用户代词，可为空", max_length=100),
                ),
                (
                    "show_forum_posts_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum posts"),
                ),
                (
                    "show_forum_post_comments_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum post comments"),
                ),
                (
                    "show_course_reviews_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的course reviews"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
