# Generated by Django 5.2.6 on 2025-10-03 05:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="展示昵称（不唯一）", max_length=100
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, help_text="头像 URL，可为空"),
                ),
                (
                    "pronouns",
                    models.CharField(blank=True, help_text="用户代词，可为空", max_length=100),
                ),
                (
                    "show_forum_posts_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum posts"),
                ),
                (
                    "show_forum_post_comments_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的forum post comments"),
                ),
                (
                    "show_course_reviews_publicly",
                    models.BooleanField(default=True, help_text="是否公开展示自己发的course reviews"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[
                    ('forumPostLiked', 'forumPostLiked'), 
                    ('forumPostCommented', 'forumPostCommented'), 
                    ('forumPostCommentLiked', 'forumPostCommentLiked'), 
                    ('forumPostCommentReplied', 'forumPostCommentReplied'), 
                    ('courseReviewLiked', 'courseReviewLiked'), 
                    ('courseReviewReplied', 'courseReviewReplied'), 
                    ('courseReviewReplyLiked', 'courseReviewReplyLiked'), 
                    ('courseReviewReplyReplied', 'courseReviewReplyReplied')
                ], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_is_anonymous', models.BooleanField(default=False)),
                ('content_preview', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('forumpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forum.forumpost')),
                ('forumpostcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forum.forumpostcomment')),
                ('coursereview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.coursereview')),
                ('coursereviewreply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.coursereviewreply')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'is_deleted', 'created_at'], name='accounts_no_user_is__d8081a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='accounts_no_user_is__c4a8be_idx'),
        ),
    ]
