import React from 'react';
import { MDXRemote } from 'next-mdx-remote/rsc';
import remarkGfm from 'remark-gfm';
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import rehypeSanitize, { defaultSchema } from 'rehype-sanitize';
import { mdxComponents } from '@/components/wiki/MdxComponents';
import type { MDXComponents } from 'mdx/types';
import { renderMarkdownToHtml } from '@/lib/markdown';

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

// Server component: render Markdown with MDX-style component mapping
export default function MarkdownRenderer({ content, className }: MarkdownRendererProps) {
  // Extend sanitize schema to allow code/pre with className, and anchors styling
  const schema = {
    ...defaultSchema,
    attributes: {
      ...defaultSchema.attributes,
      code: [
        ...(defaultSchema.attributes?.code || []),
        ['className'],
      ],
      pre: [
        ...(defaultSchema.attributes?.pre || []),
        ['className'],
      ],
      a: [
        ...(defaultSchema.attributes?.a || []),
        ['className'],
        ['href'],
        ['rel'],
        ['target'],
      ],
      span: [
        ...(defaultSchema.attributes?.span || []),
        ['className'],
      ],
      // Allow heading IDs for in-page anchors generated by rehype-slug
      h1: [
        ...(defaultSchema.attributes?.h1 || []),
        ['id'],
        ['className'],
      ],
      h2: [
        ...(defaultSchema.attributes?.h2 || []),
        ['id'],
        ['className'],
      ],
      h3: [
        ...(defaultSchema.attributes?.h3 || []),
        ['id'],
        ['className'],
      ],
      h4: [
        ...(defaultSchema.attributes?.h4 || []),
        ['id'],
        ['className'],
      ],
      h5: [
        ...(defaultSchema.attributes?.h5 || []),
        ['id'],
        ['className'],
      ],
      h6: [
        ...(defaultSchema.attributes?.h6 || []),
        ['id'],
        ['className'],
      ],
    },
  } as const;

  // Heuristic: if raw HTML contains unmatched <code> tags, fall back to safe renderer
  const openCodeTags = (content.match(/<code(\s|>)/gi) || []).length;
  const closeCodeTags = (content.match(/<\/code>/gi) || []).length;
  if (closeCodeTags < openCodeTags) {
    const html = renderMarkdownToHtml(content ?? '');
    return (
      <div className={className ?? 'prose dark:prose-invert max-w-none'}>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    );
  }

  // Heuristic: detect any curly braces or raw HTML outside fenced code blocks
  const hasSuspiciousCurly = (() => {
    const lines = (content ?? '').split(/\r?\n/);
    let inFence = false;
    for (const ln of lines) {
      if (/^\s*```/.test(ln)) { inFence = !inFence; continue; }
      if (!inFence && /[{}]/.test(ln)) return true;
    }
    return false;
  })();

  const hasRawHtmlOutsideFences = (() => {
    const lines = (content ?? '').split(/\r?\n/);
    let inFence = false;
    for (const ln of lines) {
      if (/^\s*```/.test(ln)) { inFence = !inFence; continue; }
      // very rough check for HTML-like tags
      if (!inFence && /<[^>]+>/.test(ln)) return true;
    }
    return false;
  })();

  if (hasSuspiciousCurly || hasRawHtmlOutsideFences) {
    const html = renderMarkdownToHtml(content ?? '');
    return (
      <div className={className ?? 'prose dark:prose-invert max-w-none'}>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    );
  }

  let mdxNode: React.ReactNode | null = null;
  let failed = false;
  try {
    mdxNode = (
      <MDXRemote
        source={content ?? ''}
        components={mdxComponents as unknown as MDXComponents}
        options={{
          mdxOptions: {
            remarkPlugins: [remarkGfm],
            rehypePlugins: [
              rehypeSlug,
              [rehypeAutolinkHeadings, { behavior: 'wrap' }],
              [rehypeSanitize, schema],
            ],
          },
        }}
      />
    );
  } catch {
    failed = true;
  }

  if (!failed && mdxNode) {
    return <div className={className ?? 'prose dark:prose-invert max-w-none'}>{mdxNode}</div>;
  }

  // Fallback: render with our safe markdown-to-HTML renderer when MDX compilation fails
  const html = renderMarkdownToHtml(content ?? '');
  return (
    <div className={className ?? 'prose dark:prose-invert max-w-none'}>
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </div>
  );
}

