"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # Used to build the .env file path
import environ  # django-environ: typed environment variable parser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables from .env in the project root.
# Keep secrets out of source control and configure per environment.
env = environ.Env(
    DEBUG=(bool, False),  # DEBUG defaults to False and is cast to bool
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Do NOT hardcode SECRET_KEY; read it from environment to avoid leaks.
SECRET_KEY = env("SECRET_KEY")  # Raises error if missing (good for early fail)

# Never run with DEBUG=True in production. Configure via .env or system env.
DEBUG = env("DEBUG")

# Comma-separated hostnames/IPs that this Django instance will serve.
# Example: "127.0.0.1,localhost,api.example.com"
ALLOWED_HOSTS = [h.strip() for h in env("ALLOWED_HOSTS", default="").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',      # PostgreSQL specific features (full-text search, trigram)

    # Third-party apps
    'rest_framework',           # Django REST Framework for building APIs
    'corsheaders',              # CORS handling for browser cross-origin requests
    'storages',                 # Django-storages for S3-compatible storage (R2)

    # Local apps
    'core',
    'accounts',
    'courses',
    'forum',
    'teachers',
    'wiki',
    'notifications',
]

MIDDLEWARE = [
    # Place CORS middleware near the top, before CommonMiddleware,
    # so CORS headers are added to all relevant responses.
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Use a single DATABASE_URL (e.g. postgresql://user:pass@host:5432/dbname)
# parsed by django-environ. This allows easy switching per environment.
DATABASES = {
    'default': env.db("DATABASE_URL")
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# Store timestamps in UTC (USE_TZ=True) and display/parse according to TIME_ZONE.
# Make language and timezone configurable via environment variables.
LANGUAGE_CODE = env("LANGUAGE_CODE", default="en")  # English; configurable via env
TIME_ZONE = env("TIME_ZONE", default="Asia/Hong_Kong")    # Configurable via env; default is Asia/Hong_Kong
USE_I18N = True
USE_TZ = True

# Default content language for translatable content (e.g., Wiki)
# Frontend may request a specific language via query; when absent, use this.
DEFAULT_CONTENT_LANGUAGE = env("DEFAULT_CONTENT_LANGUAGE", default="zh-CN")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # Static URL prefix; set STATIC_ROOT in production and run collectstatic

# CORS and CSRF configuration
# CORS_ALLOWED_ORIGINS controls which browser origins may access this API.
# CSRF_TRUSTED_ORIGINS lists origins (with scheme) trusted for CSRF-protected views.
CORS_ALLOWED_ORIGINS = [o.strip() for o in env("CORS_ALLOWED_ORIGINS", default="").split(",") if o.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in env("CSRF_TRUSTED_ORIGINS", default="").split(",") if o.strip()]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework minimal configuration: JSON-only API by default.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "image_upload": "100/hour",  # Image upload rate limit
    },
}

# Cache configuration (LocMem by default; override with CACHE_URL)
CACHES = {
    'default': env.cache('CACHE_URL', default='locmemcache://'),
}

# Email verification settings
AUTH_VERIFICATION_CODE_TTL_SECONDS = env.int('AUTH_VERIFICATION_CODE_TTL_SECONDS', default=60 * 15)
AUTH_VERIFICATION_REQUEST_INTERVAL_SECONDS = env.int('AUTH_VERIFICATION_REQUEST_INTERVAL_SECONDS', default=60)

# Enable Browsable API only in development for convenient exploration.
if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
        "rest_framework.renderers.BrowsableAPIRenderer"
    )

# Allow cookies to be included in cross-origin requests (frontend <-> backend)
# Ensure CORS_ALLOWED_ORIGINS and CSRF_TRUSTED_ORIGINS are set via environment.
CORS_ALLOW_CREDENTIALS = True

# Session & CSRF cookie configuration for secure, rolling sessions.
# Requirement: persist login across refresh/close, expire after 10 days of inactivity.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 10  # 10 days (in seconds)
SESSION_SAVE_EVERY_REQUEST = True       # rolling expiry: extend on each request

# Use secure cookies in non-debug environments; Lax is fine for same-site SPA API.
SESSION_COOKIE_SECURE = not DEBUG
# Use Lax for same-site (e.g., localhost:3000 -> localhost:8000) and better CSRF posture.
# If deploying frontend on a different site, switch to 'None' and ensure HTTPS.
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF token must be readable by JS to set X-CSRFToken header
CSRF_COOKIE_HTTPONLY = False

# ==================== File Storage Configuration ====================
# Use Cloudflare R2 for media files via django-storages with S3 backend
# R2 is S3-compatible with zero egress fees and built-in CDN

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": env("R2_BUCKET_NAME"),
            "access_key": env("R2_ACCESS_KEY_ID"),
            "secret_key": env("R2_SECRET_ACCESS_KEY"),
            "endpoint_url": f'https://{env("R2_ACCOUNT_ID")}.r2.cloudflarestorage.com',
            "region_name": "auto",  # R2 uses 'auto' for region
            "custom_domain": env("R2_PUBLIC_DOMAIN"),
            "default_acl": None,  # R2 doesn't use ACLs
            "file_overwrite": False,  # Keep unique filenames
            "object_parameters": {
                "CacheControl": "max-age=86400",  # 1 day cache
            },
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Image upload settings
MAX_IMAGE_SIZE = env.int("MAX_IMAGE_SIZE_MB", default=5) * 1024 * 1024  # Convert to bytes (default: 5MB)
MAX_IMAGE_PIXELS = env.int("MAX_IMAGE_PIXELS", default=50_000_000)  # Max pixels to prevent decompression bombs (default: 50MP)
ALLOWED_IMAGE_EXTENSIONS = [
    ext.strip().lower() 
    for ext in env("ALLOWED_IMAGE_TYPES", default="jpg,jpeg,png,gif,webp").split(",")
]

# Allowed public image hosts for rendering and profile avatar URLs
# Comma-separated. Example: "image.polyu.life,cdn.example.com"
ALLOWED_IMAGE_HOSTS = [
    h.strip().lower() for h in env("ALLOWED_IMAGE_HOSTS", default="image.polyu.life").split(",") if h.strip()
]
