# Generated by Django 5.2.6 on 2025-09-22 08:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.CharField(max_length=64, unique=True)),
                ("subject_code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("term_year", models.PositiveIntegerField()),
                (
                    "term_semester",
                    models.CharField(
                        choices=[
                            ("spring", "spring"),
                            ("summer", "summer"),
                            ("fall", "fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rating_score", models.FloatField(default=0)),
                ("rating_reviews_count", models.PositiveIntegerField(default=0)),
                (
                    "attr_difficulty",
                    models.CharField(
                        choices=[
                            ("veryEasy", "veryEasy"),
                            ("easy", "easy"),
                            ("medium", "medium"),
                            ("hard", "hard"),
                            ("veryHard", "veryHard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "attr_workload",
                    models.CharField(
                        choices=[
                            ("light", "light"),
                            ("moderate", "moderate"),
                            ("heavy", "heavy"),
                            ("veryHeavy", "veryHeavy"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "attr_grading",
                    models.CharField(
                        choices=[
                            ("lenient", "lenient"),
                            ("balanced", "balanced"),
                            ("strict", "strict"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                (
                    "attr_gain",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("decent", "decent"),
                            ("high", "high"),
                        ],
                        default="decent",
                        max_length=10,
                    ),
                ),
                (
                    "teachers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="教师姓名列表，例如 ['Alice','Bob']",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="courses_cou_subject_3506dc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_rating", models.FloatField(default=0)),
                (
                    "attr_difficulty",
                    models.CharField(
                        choices=[
                            ("veryEasy", "veryEasy"),
                            ("easy", "easy"),
                            ("medium", "medium"),
                            ("hard", "hard"),
                            ("veryHard", "veryHard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "attr_workload",
                    models.CharField(
                        choices=[
                            ("light", "light"),
                            ("moderate", "moderate"),
                            ("heavy", "heavy"),
                            ("veryHeavy", "veryHeavy"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "attr_grading",
                    models.CharField(
                        choices=[
                            ("lenient", "lenient"),
                            ("balanced", "balanced"),
                            ("strict", "strict"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                (
                    "attr_gain",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("decent", "decent"),
                            ("high", "high"),
                        ],
                        default="decent",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("likes_count", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "term_semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "spring"),
                            ("summer", "summer"),
                            ("fall", "fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("replies_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价",
                "verbose_name_plural": "课程评价",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseReviewReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_review_reply_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="courses.coursereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价回复",
                "verbose_name_plural": "课程评价回复",
                "ordering": ["created_at"],
            },
        ),
    ]
