# Generated by Django 5.2.6 on 2025-10-03 05:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Ensure pg_trgm extension is available
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('term_year', models.PositiveIntegerField()),
                ('term_semester', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=10)),
                ('rating_score', models.FloatField(default=0)),
                ('rating_reviews_count', models.PositiveIntegerField(default=0)),
                ('rating_recommend_count', models.PositiveIntegerField(default=0)),
                ('rating_not_recommend_count', models.PositiveIntegerField(default=0)),
                ('attr_difficulty', models.CharField(choices=[('veryEasy', 'veryEasy'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('veryHard', 'veryHard')], default='medium', max_length=10)),
                ('attr_workload', models.CharField(choices=[('light', 'light'), ('moderate', 'moderate'), ('heavy', 'heavy'), ('veryHeavy', 'veryHeavy')], default='moderate', max_length=10)),
                ('attr_grading', models.CharField(choices=[('lenient', 'lenient'), ('balanced', 'balanced'), ('strict', 'strict')], default='balanced', max_length=10)),
                ('attr_gain', models.CharField(choices=[('low', 'low'), ('decent', 'decent'), ('high', 'high')], default='decent', max_length=10)),
                ('terms', models.JSONField(blank=True, default=list, help_text='List of offered terms')),
                ('department', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_summary', models.TextField(blank=True)),
                ('selection_category', models.CharField(blank=True, max_length=100)),
                ('teaching_type', models.CharField(blank=True, max_length=100)),
                ('course_category', models.CharField(blank=True, max_length=100)),
                ('offering_department', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('credits', models.CharField(blank=True, max_length=20)),
                ('course_homepage_url', models.URLField(blank=True)),
                ('syllabus_url', models.URLField(blank=True)),
                ('curriculum', models.JSONField(blank=True, default=list, help_text='List of curriculum colleges with majors and semesters')),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.FloatField(default=0)),
                ('attr_difficulty', models.CharField(choices=[('veryEasy', 'veryEasy'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard'), ('veryHard', 'veryHard')], default='medium', max_length=10)),
                ('attr_workload', models.CharField(choices=[('light', 'light'), ('moderate', 'moderate'), ('heavy', 'heavy'), ('veryHeavy', 'veryHeavy')], default='moderate', max_length=10)),
                ('attr_grading', models.CharField(choices=[('lenient', 'lenient'), ('balanced', 'balanced'), ('strict', 'strict')], default='balanced', max_length=10)),
                ('attr_gain', models.CharField(choices=[('low', 'low'), ('decent', 'decent'), ('high', 'high')], default='decent', max_length=10)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('only_text', models.BooleanField(default=False, help_text='如果为真，则仅文本评价（不含星级/维度）')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_year', models.PositiveIntegerField(blank=True, null=True)),
                ('term_semester', models.CharField(blank=True, choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=10)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course review',
                'verbose_name_plural': 'Course reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.coursereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course review like',
                'verbose_name_plural': 'Course review likes',
            },
        ),
        migrations.CreateModel(
            name='CourseReviewReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_review_reply_targets', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursereview')),
            ],
            options={
                'verbose_name': 'Course review reply',
                'verbose_name_plural': 'Course review replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReviewReplyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.coursereviewreply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course review reply like',
                'verbose_name_plural': 'Course review reply likes',
            },
        ),
        migrations.CreateModel(
            name='CourseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('recommend', 'recommend'), ('notRecommend', 'notRecommend')], max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course vote',
                'verbose_name_plural': 'Course votes',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='courses_cou_course__119e53_idx'),
        ),
        # Add trigram indexes for better search performance on Chinese text
        migrations.AddIndex(
            model_name='course',
            index=GinIndex(fields=['subject_code'], name='courses_subject_code_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='course',
            index=GinIndex(fields=['title'], name='courses_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='course',
            index=GinIndex(fields=['department'], name='courses_department_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        # Add index for ordering
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-last_updated'], name='courses_last_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('author', 'course'), name='unique_course_review_per_user'),
        ),
        # Add trigram index for course review content search
        migrations.AddIndex(
            model_name='coursereview',
            index=GinIndex(fields=['content'], name='coursereview_content_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='coursereviewlike',
            index=models.Index(fields=['review', 'user'], name='courses_cou_review__af06b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereviewlike',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique_review_like'),
        ),
        migrations.AddIndex(
            model_name='coursereviewreplylike',
            index=models.Index(fields=['reply', 'user'], name='courses_cou_reply_i_c927d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursereviewreplylike',
            constraint=models.UniqueConstraint(fields=('user', 'reply'), name='unique_reply_like'),
        ),
        migrations.AddIndex(
            model_name='coursevote',
            index=models.Index(fields=['course', 'user'], name='courses_cou_course__c5a2d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursevote',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_course_vote'),
        ),
    ]
