# Generated by Django 5.2.6 on 2025-09-22 08:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("subject_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject_code", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("term_year", models.PositiveIntegerField()),
                (
                    "term_semester",
                    models.CharField(
                        choices=[
                            ("spring", "spring"),
                            ("summer", "summer"),
                            ("fall", "fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rating_score", models.FloatField(default=0)),
                ("rating_reviews_count", models.PositiveIntegerField(default=0)),
                ("rating_recommend_count", models.PositiveIntegerField(default=0)),
                ("rating_not_recommend_count", models.PositiveIntegerField(default=0)),
                (
                    "attr_difficulty",
                    models.CharField(
                        choices=[
                            ("veryEasy", "veryEasy"),
                            ("easy", "easy"),
                            ("medium", "medium"),
                            ("hard", "hard"),
                            ("veryHard", "veryHard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "attr_workload",
                    models.CharField(
                        choices=[
                            ("light", "light"),
                            ("moderate", "moderate"),
                            ("heavy", "heavy"),
                            ("veryHeavy", "veryHeavy"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "attr_grading",
                    models.CharField(
                        choices=[
                            ("lenient", "lenient"),
                            ("balanced", "balanced"),
                            ("strict", "strict"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                (
                    "attr_gain",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("decent", "decent"),
                            ("high", "high"),
                        ],
                        default="decent",
                        max_length=10,
                    ),
                ),
                ("terms", models.JSONField(blank=True, default=list, help_text="List of offered terms")),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("selection_category", models.CharField(blank=True, max_length=100)),
                ("teaching_type", models.CharField(blank=True, max_length=100)),
                ("course_category", models.CharField(blank=True, max_length=100)),
                ("offering_department", models.CharField(blank=True, max_length=200)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                    ),
                ),
                ("credits", models.CharField(blank=True, max_length=20)),
                ("course_homepage_url", models.URLField(blank=True)),
                ("syllabus_url", models.URLField(blank=True)),
                ("curriculum", models.JSONField(blank=True, default=list, help_text="List of curriculum colleges with majors and semesters")),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "indexes": [
                    models.Index(fields=["subject_id"], name="courses_cou_subject_3506dc_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_rating", models.FloatField(default=0)),
                (
                    "attr_difficulty",
                    models.CharField(
                        choices=[
                            ("veryEasy", "veryEasy"),
                            ("easy", "easy"),
                            ("medium", "medium"),
                            ("hard", "hard"),
                            ("veryHard", "veryHard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "attr_workload",
                    models.CharField(
                        choices=[
                            ("light", "light"),
                            ("moderate", "moderate"),
                            ("heavy", "heavy"),
                            ("veryHeavy", "veryHeavy"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "attr_grading",
                    models.CharField(
                        choices=[
                            ("lenient", "lenient"),
                            ("balanced", "balanced"),
                            ("strict", "strict"),
                        ],
                        default="balanced",
                        max_length=10,
                    ),
                ),
                (
                    "attr_gain",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("decent", "decent"),
                            ("high", "high"),
                        ],
                        default="decent",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("only_text", models.BooleanField(default=False, help_text="如果为真，则仅文本评价（不含星级/维度）")),
                ("likes_count", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "term_semester",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "spring"),
                            ("summer", "summer"),
                            ("fall", "fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("replies_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价",
                "verbose_name_plural": "课程评价",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("author", "course"), name="unique_course_review_per_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseReviewReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_review_reply_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="courses.coursereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价回复",
                "verbose_name_plural": "课程评价回复",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "review",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="courses.coursereview"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "课程评价点赞",
                "verbose_name_plural": "课程评价点赞",
                "indexes": [
                    models.Index(fields=["review", "user"], name="courses_cou_review_user_like_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "review"), name="unique_review_like"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseReviewReplyLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "reply",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="courses.coursereviewreply"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "课程评价回复点赞",
                "verbose_name_plural": "课程评价回复点赞",
                "indexes": [
                    models.Index(fields=["reply", "user"], name="courses_cou_reply_user_like_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "reply"), name="unique_reply_like"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("recommend", "recommend"),
                            ("notRecommend", "notRecommend"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course vote",
                "verbose_name_plural": "Course votes",
                "indexes": [
                    models.Index(fields=["course", "user"], name="courses_cou_course_user_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "course"), name="unique_course_vote"),
                ],
            },
        ),
    ]
